// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQvJ1Bsmi_VMCzPam-YWMtQZLOaWuWtiI',
    appId: '1:39358873780:web:d4d587f46ba8bc4fc517e1',
    messagingSenderId: '39358873780',
    projectId: 'payflow-adfc8',
    authDomain: 'payflow-adfc8.firebaseapp.com',
    storageBucket: 'payflow-adfc8.appspot.com',
    measurementId: 'G-90QHGD2HXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDluKcI3T1B7Q-Q-58e2G5nvsrN5tgMpTs',
    appId: '1:39358873780:android:4e02f93f715d3e49c517e1',
    messagingSenderId: '39358873780',
    projectId: 'payflow-adfc8',
    storageBucket: 'payflow-adfc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0up-Zc5tQrAJ_vfMfSwz6P8HgW5x4S7A',
    appId: '1:39358873780:ios:544a682fd3a9000cc517e1',
    messagingSenderId: '39358873780',
    projectId: 'payflow-adfc8',
    storageBucket: 'payflow-adfc8.appspot.com',
    iosClientId: '39358873780-a374sa5l17giar2qhs5h2njn614eprhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.playflow',
  );
}
